-- MySQL Script generated by MySQL Workbench
-- Thu 03 Feb 2022 09:47:35 AM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema drustvena_mreza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema drustvena_mreza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `drustvena_mreza` DEFAULT CHARACTER SET utf8 ;
USE `drustvena_mreza` ;

-- -----------------------------------------------------
-- Table `drustvena_mreza`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drustvena_mreza`.`user` (
  `uderID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`uderID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drustvena_mreza`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drustvena_mreza`.`post` (
  `postID` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(200) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `user_uderID` INT NOT NULL,
  PRIMARY KEY (`postID`),
  INDEX `fk_post_user_idx` (`user_uderID` ASC) ,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_uderID`)
    REFERENCES `drustvena_mreza`.`user` (`uderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drustvena_mreza`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drustvena_mreza`.`comment` (
  `commentID` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(150) NOT NULL,
  `post_postID` INT NOT NULL,
  `user_uderID` INT NOT NULL,
  PRIMARY KEY (`commentID`),
  INDEX `fk_comment_post1_idx` (`post_postID` ASC) ,
  INDEX `fk_comment_user1_idx` (`user_uderID` ASC) ,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_postID`)
    REFERENCES `drustvena_mreza`.`post` (`postID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_uderID`)
    REFERENCES `drustvena_mreza`.`user` (`uderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drustvena_mreza`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drustvena_mreza`.`like` (
  `likeID` INT NOT NULL AUTO_INCREMENT,
  `comment_commentID` INT NOT NULL,
  `post_postID` INT NOT NULL,
  PRIMARY KEY (`likeID`),
  INDEX `fk_like_comment1_idx` (`comment_commentID` ASC) ,
  INDEX `fk_like_post1_idx` (`post_postID` ASC) ,
  CONSTRAINT `fk_like_comment1`
    FOREIGN KEY (`comment_commentID`)
    REFERENCES `drustvena_mreza`.`comment` (`commentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_post1`
    FOREIGN KEY (`post_postID`)
    REFERENCES `drustvena_mreza`.`post` (`postID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
